# **recover**
## **recover란?**
- **recover()** 함수는 **패니킹** 작업으로부터 **프로그램의 제어권**을 다시 얻어 계속 **이어나가**게 해준다.
- **recover()** 는 반드시 **defer 안**에서 사용 해야한다.
- defer 구문 안에서 recover()를 호출하면 **패닉 내부 상황**을 **error** 값으로 **복원**할 수 있다.
- **recover()** 로 패닉을 복원한 후에는 **패니킹 상황이 종료**되고 함수 **반환 타입의 제로값**이 **반환**된다.

<br>

**recover 사용 예시 코드**
~~~go
func main() {
    fmt.Println("result:", , divide(1, 0))
}

func divide (a, b int) (int error) {
    defer func(){
        if err := recover(); err != nil {
            fmt.Println(err)
        }
    }()

    return a/b
}
~~~
~~~
실행 결과

runtime error: integer divide by zero
result: 0
~~~

<br>
<!-- 
---
## **recover** VS **try-finally**
- **recover**는 파이썬의 **try-finally** 블록과 유사하다.
- 다음 코드는 매개변수로 받은 함수를 실행한 후 **패닉**이 발생하면 **error 정보**를 가져와 **출력**한다.
    ~~~go

    ~~~ -->